config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  authenticated :admin do
    namespace :admin do
      root 'tasks#index'
      resources :admins, only: %i[index show new create]
      resource :dashboard, only: %i[show], controller: :dashboard
      resources :tasks, only: %i[index show update] do
        resources :comments, only: %i[new create]
      end
      resources :users, only: %i[index show new create]
    end
  end

  authenticated :user do
    root 'tasks#index'
    resources :users, only: %i[show]
    resource :dashboard, only: %i[show], controller: :dashboard
    resources :tasks, only: %i[index new show create] do
      resources :comments, only: %i[new create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: %i[index show create] do
        resources :comments, only: %i[index show create]
      end
    end
  end

  root 'static_pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :comments, as: :commentator, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :commentator, polymorphic: true

  validate :body
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :admin, optional: :true
  has_many :comments, dependent: :destroy

  enum status: [ :active, :closed ]

  def change_status
    active? ? closed! : active!
  end

  def supported_admin
   admin ? admin.email : I18n.t('no_supported_admin')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :tasks, dependent: :destroy
  has_many :comments, as: :commentator, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  devise_group :visitor, contains: [:user, :admin]
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < BaseControllers::BaseUserController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create!(comment_params)
    redirect_to task_path(@task)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(commentator: current_user)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < BaseControllers::BaseUserController
  def index
    @tasks = current_user.tasks
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render action: 'new'
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < BaseControllers::BaseUserController
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/show.html.slim
.log-out-panel.pull-right
  strong= "#{t('logged_in_as')} #{current_admin.email} "
  = link_to fa_icon('sign-out', text:  'Sign out'), destroy_admin_session_path,
    method: :delete, class: 'btn btn-info btn-square'
.user-pannel.pull-left
  = link_to fa_icon('vcard', text: 'Your profile'), 
    admin_admin_path(current_admin), class: 'btn btn-info btn-square'
  = link_to fa_icon('table', text: 'All tasks'), admin_tasks_path,
    class: 'btn btn-info btn-square'
  = link_to fa_icon('users', text: 'Users'), admin_users_path,
    class: 'btn btn-info btn-square'
  = link_to fa_icon('wrench', text: 'Admins'), admin_admins_path,
    class: 'btn btn-info btn-square'

app/views/dashboard/show.html.slim
.log-out-panel.pull-right
  strong= "#{t('logged_in_as')} #{current_user.email} "
  = link_to fa_icon('sign-out', text:  'Sign out'), destroy_user_session_path,
    method: :delete, class: 'btn btn-info btn-square'
.user-pannel.pull-left
  = link_to fa_icon('vcard', text: 'Your profile'), user_path(current_user), 
    class: 'btn btn-info btn-square'
  = link_to fa_icon('table', text: 'All tasks'), tasks_path,
    class: 'btn btn-info btn-square'
  = link_to fa_icon("plus", text: 'New Task'), 
    new_task_path, class: 'btn btn-info btn-square'